# Generated by Django 6.0.2 on 2026-03-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_doctor',
            old_name='doctor_address',
            new_name='specialization',
        ),
    ]
