# Generated by Django 6.0.2 on 2026-03-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_doctor_address_tbl_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='doctor_address',
            field=models.TextField(null=True),
        ),
    ]
