# Generated by Django 6.0.2 on 2026-02-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_patient',
        ),
    ]
