# Generated by Django 6.0.2 on 2026-02-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0002_delete_tbl_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_contact', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_gender', models.CharField(max_length=20)),
                ('patient_address', models.TextField()),
                ('patient_photo', models.FileField(upload_to='patientDocs/')),
                ('patient_password', models.CharField(max_length=20)),
                ('patient_status', models.IntegerField(default=0)),
            ],
        ),
    ]
