# Generated by Django 5.2.11 on 2026-02-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('doctor_contact', models.CharField(max_length=20)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_gender', models.CharField(max_length=20)),
                ('doctor_address', models.TextField()),
                ('doctor_photo', models.FileField(upload_to='doctorDocs/')),
                ('doctor_password', models.CharField(max_length=20)),
                ('doctor_status', models.IntegerField(default=0)),
            ],
        ),
    ]
