# Generated by Django 6.0.2 on 2026-03-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_delete_tbl_location'),
        ('Guest', '0005_tbl_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_doctor',
        ),
    ]
